Models/Candidate.cs
using System.ComponentModel.DataAnnotations;

namespace BtkAkademi.Models
{
    public class Candidate
    {
        [Required(ErrorMessage ="E-Mail is required.")]
        public String? Email { get; set; } = String.Empty;
                [Required(ErrorMessage ="FirstName is required.")]
        public String? FirstName { get; set; } = String.Empty;
                [Required(ErrorMessage ="LastName is required.")]
        public String? LastName { get; set; } = String.Empty;
        public String? FullName => $"{FirstName} {LastName?.ToUpper()}";
        public int? Age { get; set; }
        public String? SelectedCourse { get; set; } = String.Empty;
        public DateTime ApplyAt { get; set; }
        public Candidate()
        {
            ApplyAt = DateTime.Now;
        }        

    }
}

Models/ErrorViewModel.cs
namespace BtkAkademi.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Repository.cs
namespace BtkAkademi.Models
{
    public static class Repository
    {
        private static List<Candidate> applications = new();
        public static IEnumerable<Candidate> Applications => applications;

        public static void Add(Candidate candidate)
        {
            applications.Add(candidate);
        }
    }
}

Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using BtkAkademi.Models;

namespace BtkAkademi.Controllers
{
    public class CourseController : Controller
    {
        public IActionResult Index()
        {
            var model = Repository.Applications;
            return View(model); 
        }
        public IActionResult Apply()
        {
            return View(); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Apply([FromForm] Candidate model)
        {
            if (Repository.Applications.Any(c => c.Email.Equals(model.Email)))
            {
                ModelState.AddModelError("","There is already an application for you.");
            }
            {
                
            }

            if (ModelState.IsValid)
            {
                Repository.Add(model);
                return View("Feedback",model); 
            } 
            return View();
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BtkAkademi.Models;

namespace BtkAkademi.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Course/Apply.cshtml
@model Candidate

<div class="display-6">
    Apply
</div>
<form method="post" asp-action="Apply">
    <div class="text-danger" asp-validation-summary="All"></div>

    <div class="form-group my-2">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
    </div>

    <div class="form-group my-2">
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" class="form-control" />
    </div>

    <div class="form-group my-2">
        <label asp-for="LastName"></label>
        <input asp-for="LastName" class="form-control" />
    </div>

    <div class="form-group my-2">
        <label asp-for="Age"></label>
        <select asp-for="Age" class="form-control" name="Age">
            <option value="18">18</option>
            <option value="19">19</option>
            <option value="20">20</option>
            <option value="21">21</option>
            <option value="22">22</option>
            <option value="23">23</option>
        </select>
    </div>

    <fieldset>
        <legend>Select One Course</legend>
        <p>
            <input id="mvc" type="radio" asp-for="SelectedCourse" value="ASP.NET Core MVC" />
            <label>ASP.NET Core MVC</label>
        </p>
        <p>
            <input id="api" type="radio" asp-for="SelectedCourse" value="ASP.NET Core API" checked />
            <label>ASP.NET Core API</label>
        </p>
        <p>
            <input id="blozar" type="radio" asp-for="SelectedCourse" value="Blozar" />
            <label>Blozar</label>
        </p>
    </fieldset>

    <div>
        <button class="btn btn-primary" type="submit">Apply</button>
        <a class="btn btn-warning" asp-controller="Home" asp-action="Index">Home</a>
    </div>
</form>

Views/Course/Feedback.cshtml
@model Candidate

<div>
    <h3 class="display-4">Congratulations @Model.FullName</h3>
    <p class="lead">Your applications has been <mark>accepted.</mark></p>
    <p class="lead">Many thanks for your interest.</p>
    <hr />
    <blockquote class="blockquote">
        You have enrolled to @Model.SelectedCourse course.
    </blockquote>
    <p class="text-muted">You applied at @Model.ApplyAt</p>
    <div class="btn-group">
        <a class="btn btn-outline-success" asp-action="Index">Applications</a>
        <a class="btn btn-success" asp-action="Index" asp-controller="Home">Home</a>
    </div>
</div>

Views/Course/Index.cshtml
@model IEnumerable<Candidate>

@if (Model.Count() > 0)
{
    <h6 class="display-6">
        Applications(@Model.Count())
    </h6>
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>Email</th>
                <th>Full Name</th>
                <th>Apply At</th>
                <th>Course</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Candidate candidate in Model)
            {
                <tr>
                    <td>@candidate.Email</td>
                    <td>@candidate.FullName</td>
                    <td>@candidate.ApplyAt</td>
                    <td>@candidate.SelectedCourse</td>
                </tr>   
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-info">
        There is no application. Please click here to
        <a class="alert-link" asp-action="Apply">apply.</a>

    </div>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">BTK Akademi</h1>
    <p>
        <a class="btn btn-primary" asp-controller="Course" asp-action="Apply">Apply</a>
    </p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BtkAkademi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BtkAkademi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BtkAkademi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Apply">Apply</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Applications</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BtkAkademi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>